- src/mugesh012/UseArthmOpr.java
COD-38 Use Arithmetic Operators
> COD-38 Use Arithmetic Operators

- src/mugesh012/TableBrkCnte.java
> COD-39 for table

- src/mugesh012/MethodConcept.java
> COD-41 method program

- src/mugesh012/ArraysDemo1.java
> COD-40 array demo

- src/priya/ForeachJava.java
- src/priya/IfelseJava.java
am using for each to print all names
> Cod 48 for each program

- src/priya/SwitchCaseJava.java
> COD-43 SwitchCaseJava.java

- src/priya/WhileloopJava.java
> COD-42 creating new folder

- src/priya/OutputJava.java
> COD-44 output java

- src/sushmitha/SwitchDemo.java
> COD-57switch

- src/Manoj/ArrayList2.java
> List2 COD-90

- src/Manoj/Enum1.java
> Enum1 COD-85

- src/mugesh012/EnumDemo1.java
> enum COD-81

- src/mugesh012/ArrayListDemo1.java
> COD-79 arraylist

- src/Manoj/ArrayList1.java
> List1 COD-88

- src/Manoj/HM.java
> Hash Map COD-91

- src/mugesh012/ArrayDemo2.java
> COD-92 arraylist use numbers

- src/mugesh012/ArrayClass.java
- src/mugesh012/MainDriver.java
> Cod 93 ArrayList 

- src/Manoj/Date.java
> Date Time  COD-86

- src/mugesh012/ArrayClass.java
- src/mugesh012/MainDriver.java
> Cod 93 merge error facing

- bin/.gitignore
- src/sushmitha/For.java
> for Cod 49
